[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"
  VITE_SITE_URL = "https://soukna.netlify.app"
  VITE_BASE_PATH = "/"
  VITE_SUPABASE_URL = "https://dhgfbdxndsavbdneycnv.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRoZ2ZiZHhuZHNhdmJkbmV5Y252Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY5NjU2MTcsImV4cCI6MjA5MjU0MTYxN30.NUfILP9HBSeXn51kOWOWPacsDb5JyrJLjF5nrZNin38"
  VITE_GEMINI_API_KEY = "AIzaSyCF72B4kohRDcbAPRJdabQWMnWz5hPr8gw"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
